### PR TITLE
Added bracketing to LineSearch

### PR DESCRIPTION
**Pull request by DirkToewe**
LineSearch now keeps track of the upper and lower bounds of the search range which drastically reduces the number of search steps in some cases.

Btw: Love the library! Minimalistic and super clean code!

### CODE REVIEW

**Comment by yixuan** [comment]
This looks really cool, thank you for your contribution!

I'm considering to modularize the line search algorithm, so would you like to implement the bracket line search algorithm under a different class name, such as `BracketLineSearch`? You can create a new file and add your authorship to it.

I tend to keep the old line search algorithm based on three reasons: first, it is the "textbook" implementation and hence can be kept as a reference; second, probably there is no line search algorithm that is uniformly better than the other, so it is better to add an option than to replace the old one; third, `std::isinf()` is a C++ 11 function and the existing code is C++ 98 compatible.

After this is done I'll add a template parameter to `LBFGSSolver`, so that users can choose their favourite line search algorithm at compile time. Actually I had this in mind when I first wrote this tiny library but didn't get a change to implement more advanced line search algorithms.

**Comment by DirkToewe** [comment]
Yeah that makes perfect sense. I moved the changes to a separate file and added a little piece of test code. Feel free to make as many more changes as You have to. Once You've added a template parameter for the line search method, I might implement another line search algorithm from Jorge Nocedal's book <i>Numerical Optimization</i>.

**Comment by yixuan** [comment]
Cool! Thank you so much.

**Comment by yixuan** [comment]
Hi @DirkToewe, just want to let you know that I have cleaned the code and added the line search algorithm as a template template parameter. You can see the example in the readme.
New line search algorithms can added in the same manner.

**Pull request merged**
